---
title: Machine Learning in Environmental Science
description: Welcome to the EDS 232 Website
format:
  html:
    toc: true
    toc-location: left
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.4
  kernelspec:
    display_name: EDS 232
    language: python
    name: eds232_env
---

![Image created using the Midjourney image generation tool]

  [Image created using the Midjourney image generation tool]: img/MLRobotLearnBanner.png

## Course Description

Machine learning is a field of inquiry devoted to understanding and building methods that "learn," that is, methods that leverage data to improve performance on some set of tasks. In this course, we focus on the core concepts of machine learning that beginning ML researchers must know. We cover "classical machine learning" primarily using R and explore applications to environmental science. To understand broader concepts of artificial intelligence or deep learning, a strong fundamental knowledge of machine learning is indispensable.

## Teaching Team

**Instructor:** Mateo Robbins (mjrobbins\@ucsb.edu)

**Student hours:** Tuesdays 10:45am (Bren 1424)

**Teaching Assistant:** Annie Adams (aradams\@ucsb.edu)

**Student hours:** Thursdays 11:00am (Bren 1520 - Oak Room)

## Important Links

-   [Link to full course syllabus]

  [Link to full course syllabus]: https://docs.google.com/document/d/12VFjVN8E9cN_CHXs2mXIuIHqk6DSQklKjcRyKQnVDgE/edit?usp=sharing

## Weekly Course Schedule

**Lecture:** TTh 9:30am - 10:45am (Bren 1424)

**Sections:** Th 1:00pm - 1:50pm or 2:00 - 2:50pm (Bren 3022)

## Learning Objectives

The goal of EDS 232 is to equip students with a strong foundation in the core concepts of machine learning. By the end of the course, students should be able to:

-   Explain key machine learning concepts such as classification, regression, overfitting, and the trade-off in model complexity.

-   Identify and justify appropriate data preprocessing techniques and integrate them into machine learning pipelines.

-   Demonstrate an intuitive understanding of common machine learning algorithms.

-   Build supervised machine learning pipelines using Python and scikit-learn on real-world datasets.

-   Apply best practices for machine learning development so that your models generalize to data and tasks in the real world. Measure and contrast the performance of various models

## Course Requirements

### Computing

-   [Minimum MEDS device requirements]

  [Minimum MEDS device requirements]: https://ucsb-meds.github.io/computer_reqs.html

### Textbook

-   [Intro to Statistical Learning with Python] (ISL)

  [Intro to Statistical Learning with Python]: https://www.statlearning.com/

## Course Topics

+-------------+------------+----------------------------------------------------------+--------------------------+
| **Week \#** | **Dates**  | **Lecture**                                              | **Reading**              |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 1           | 1/7, 1/9   | [Introduction]                                           | ISL Ch. 1, 2.1           |
|             |            |                                                          |                          |
|             |            | [Linear Regression and ML Modeling Fundamentals I]       |                          |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 2           | 1/14, 1/16 | [Regularized Regression and ML Modeling Fundamentals II] | ISL Ch. 5.1.1-5.1.4, 6.2 |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 3           | 1/21, 1/23 | [Logistic Regression, Classification]                    | ISL Ch. 4.1-4.4          |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 4           | 1/28, 1/30 | [K-nearest neighbors, Decision Trees]                    | ISL Ch. 2.2.3, 8.1       |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 5           | 2/3, 2/6   | [Bagging, Random Forest]                                 | ISL Ch. 8.2.1, 8.2.2     |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 6           | 2/11, 2/13 | Guest Lecture                                            |                          |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 7           | 2/18, 2/20 | [Gradient Boosting]                                      | 8.2.3, 8.2.5, 10.7.2     |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 8           | 2/25, 2/27 | [Clustering]                                             | 12.4                     |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 9           | 3/4, 3/6   | [SVM]                                                    | 9.2                      |
+-------------+------------+----------------------------------------------------------+--------------------------+
| 10          | 3/11, 3/13 | [Deep Learning], Kaggle                                  |                          |
+-------------+------------+----------------------------------------------------------+--------------------------+

  [Introduction]: https://ucsb.box.com/s/maqfl2rorjjbekb23ek98b3odshuvcq2
  [Linear Regression and ML Modeling Fundamentals I]: https://ucsb.box.com/s/3krktrjmagi8sbo3mwg2t4rc57qtu100
  [Regularized Regression and ML Modeling Fundamentals II]: https://ucsb.box.com/s/rbdkrkiue88ggqeutgua1xzeh44lj5aw
  [Logistic Regression, Classification]: https://ucsb.box.com/s/i5ymtx2fv1cn2tonnt7ibt03gop19vey
  [K-nearest neighbors, Decision Trees]: https://ucsb.box.com/s/vr9dc4t9llrultj6sgmxceb5yxi84n29
  [Bagging, Random Forest]: https://ucsb.box.com/s/9zti9j0qb53ontnyi80pzmpupcwq5am5
  [Gradient Boosting]: https://ucsb.box.com/s/29xmz1fl3vac53wlqako2v2cbry3mk7s
  [Clustering]: https://ucsb.box.com/s/65pedl14hkolxakt0c0idngnvlyih0uz
  [SVM]: https://ucsb.box.com/s/kz89ngfgiztgw43kec2qra5j0sjqovmb
  [Deep Learning]: https://ucsb.box.com/s/regphuofzz57rnnjogojow41dldxbpqn